### ISSUE TITLE
rules?

### ISSUE THREAD

**Issue by Soundmatters** [MarcosSueiro/nypr-archives-ingest-scripts#9]
I'm wonder if there is an easy way to build in “rules.”  That’s to say, a reference at the top of each column to state which values in each are a passing (vs. failing) value. Like: Abstract/1, assetDate/1+, etc.  Right now genre might be genre/1 but I know that you are considering changing that to genre/1+

**Comment by MarcosSueiro** [comment]
Merged with https://github.com/MarcosSueiro/nypr-archives-ingest-scripts/issues/8
